[metadata]
name = verible_py
version = 0.0.4157
description = Pre-commit hook for verible (https://chipsalliance.github.io/verible/)
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/chipsalliance/verible
author = Henner Zeller
author_email = h.zeller@acm.org
license = MIT
license_files = LICENSE
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: Implementation :: CPython
    Programming Language :: Python :: Implementation :: PyPy

[options]
python_requires = >=3.10
setup_requires =
    setuptools-download

[setuptools_download]
download_scripts =
    [verible-verilog-lint]
    group = verible-verilog-lint
    marker = sys_platform == "linux" and platform_machine == "x86_64"
    url = https://github.com/chipsalliance/verible/releases/download/v0.0-4157-gfdbac312/verible-v0.0-4157-gfdbac312-linux-static-x86_64.tar.gz
    sha256 = 9e7ead54bc5efcc31476eb87dd970fe51314e8ca6bd00e0646e1ea6cde137448
    extract = tar
    extract_path = verible-v0.0-4157-gfdbac312/bin/verible-verilog-lint
    [verible-verilog-lint]
    group = verible-verilog-lint
    marker = sys_platform == "linux" and platform_machine == "arm64"
    url = https://github.com/chipsalliance/verible/releases/download/v0.0-4157-gfdbac312/verible-v0.0-4157-gfdbac312-linux-static-arm64.tar.gz
    sha256 = e87ac5918115dc17e68bec8f32ed01901bfaeffb41c29daf5743bbd8d271d3a0
    extract = tar
    extract_path = verible-v0.0-4157-gfdbac312/bin/verible-verilog-lint
    [verible-verilog-lint.exe]
    group = verible-verilog-lint
    marker = sys_platform == "win32" and platform_machine == "AMD64"
    marker = sys_platform == "cygwin" and platform_machine == "x86_64"
    url = https://github.com/chipsalliance/verible/releases/download/v0.0-4157-gfdbac312/verible-v0.0-4157-gfdbac312-win64.zip
    sha256 = 586679435c3bbb851c48c68de136d8d231bbc93be114467feb3c0d1c60b69bfc
    extract = zip
    extract_path = verible-v0.0-4157-gfdbac312-win64/verible-verilog-lint.exe
    [verible-verilog-lint]
    group = verible-verilog-lint
    marker = sys_platform == "darwin" and platform_machine == "x86_64"
    marker = sys_platform == "darwin" and platform_machine == "arm64"
    url = https://github.com/chipsalliance/verible/releases/download/v0.0-4157-gfdbac312/verible-v0.0-4157-gfdbac312-macOS.tar.gz
    sha256 = c0c8d0ddb2e25dd940f5c5a4f7707a4bf0df91b6908b6640aaa32f409c2d6d26
    extract = tar
    extract_path = verible-v0.0-4157-gfdbac312-macOS/bin/verible-verilog-lint
    [verible-verilog-format]
    group = verible-verilog-format
    marker = sys_platform == "linux" and platform_machine == "x86_64"
    url = https://github.com/chipsalliance/verible/releases/download/v0.0-4157-gfdbac312/verible-v0.0-4157-gfdbac312-linux-static-x86_64.tar.gz
    sha256 = 9e7ead54bc5efcc31476eb87dd970fe51314e8ca6bd00e0646e1ea6cde137448
    extract = tar
    extract_path = verible-v0.0-4157-gfdbac312/bin/verible-verilog-format
    [verible-verilog-format]
    group = verible-verilog-format
    marker = sys_platform == "linux" and platform_machine == "arm64"
    url = https://github.com/chipsalliance/verible/releases/download/v0.0-4157-gfdbac312/verible-v0.0-4157-gfdbac312-linux-static-arm64.tar.gz
    sha256 = e87ac5918115dc17e68bec8f32ed01901bfaeffb41c29daf5743bbd8d271d3a0
    extract = tar
    extract_path = verible-v0.0-4157-gfdbac312/bin/verible-verilog-format
    [verible-verilog-format.exe]
    group = verible-verilog-format
    marker = sys_platform == "win32" and platform_machine == "AMD64"
    marker = sys_platform == "cygwin" and platform_machine == "x86_64"
    url = https://github.com/chipsalliance/verible/releases/download/v0.0-4157-gfdbac312/verible-v0.0-4157-gfdbac312-win64.zip
    sha256 = 586679435c3bbb851c48c68de136d8d231bbc93be114467feb3c0d1c60b69bfc
    extract = zip
    extract_path = verible-v0.0-4157-gfdbac312-win64/verible-verilog-format.exe
    [verible-verilog-format]
    group = verible-verilog-format
    marker = sys_platform == "darwin" and platform_machine == "x86_64"
    marker = sys_platform == "darwin" and platform_machine == "arm64"
    url = https://github.com/chipsalliance/verible/releases/download/v0.0-4157-gfdbac312/verible-v0.0-4157-gfdbac312-macOS.tar.gz
    sha256 = c0c8d0ddb2e25dd940f5c5a4f7707a4bf0df91b6908b6640aaa32f409c2d6d26
    extract = tar
    extract_path = verible-v0.0-4157-gfdbac312-macOS/bin/verible-verilog-format
