[metadata]
name = verible_py
version = 0.0.4296
description = Pre-commit hook for verible (https://chipsalliance.github.io/verible/)
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/chipsalliance/verible
author = Henner Zeller
author_email = h.zeller@acm.org
license = MIT
license_files = LICENSE
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: Implementation :: CPython
    Programming Language :: Python :: Implementation :: PyPy

[options]
python_requires = >=3.10
setup_requires =
    setuptools-download

[setuptools_download]
download_scripts =
    [verible-verilog-lint]
    group = verible-verilog-lint
    marker = sys_platform == "linux" and platform_machine == "x86_64"
    url = https://github.com/chipsalliance/verible/releases/download/v0.0-4296-g0f262651/verible-v0.0-4296-g0f262651-linux-static-x86_64.tar.gz
    sha256 = 8569defb891d2316067613ea00442af28a7a09d405d95b54c0c91f9942d26635
    extract = tar
    extract_path = verible-v0.0-4296-g0f262651/bin/verible-verilog-lint
    [verible-verilog-lint]
    group = verible-verilog-lint
    marker = sys_platform == "linux" and platform_machine == "arm64"
    url = https://github.com/chipsalliance/verible/releases/download/v0.0-4296-g0f262651/verible-v0.0-4296-g0f262651-linux-static-arm64.tar.gz
    sha256 = e4a70e9920b6a24ce35045d4c9457d7d9185efc3c534a35ff55ef0262578b4e0
    extract = tar
    extract_path = verible-v0.0-4296-g0f262651/bin/verible-verilog-lint
    [verible-verilog-lint.exe]
    group = verible-verilog-lint
    marker = sys_platform == "win32" and platform_machine == "AMD64"
    marker = sys_platform == "cygwin" and platform_machine == "x86_64"
    url = https://github.com/chipsalliance/verible/releases/download/v0.0-4296-g0f262651/verible-v0.0-4296-g0f262651-win64.zip
    sha256 = 4590841d91dadb108879aa261dbfd7081db06360484a7a21470174bf6fb3cf80
    extract = zip
    extract_path = verible-v0.0-4296-g0f262651-win64/verible-verilog-lint.exe
    [verible-verilog-lint]
    group = verible-verilog-lint
    marker = sys_platform == "darwin" and platform_machine == "x86_64"
    marker = sys_platform == "darwin" and platform_machine == "arm64"
    url = https://github.com/chipsalliance/verible/releases/download/v0.0-4296-g0f262651/verible-v0.0-4296-g0f262651-macOS.tar.gz
    sha256 = fc397ee02b144184a3cce6d26efb8b9d3e41528e63c95a57cd3bf37dec2b52a4
    extract = tar
    extract_path = verible-v0.0-4296-g0f262651-macOS/bin/verible-verilog-lint
    [verible-verilog-format]
    group = verible-verilog-format
    marker = sys_platform == "linux" and platform_machine == "x86_64"
    url = https://github.com/chipsalliance/verible/releases/download/v0.0-4296-g0f262651/verible-v0.0-4296-g0f262651-linux-static-x86_64.tar.gz
    sha256 = 8569defb891d2316067613ea00442af28a7a09d405d95b54c0c91f9942d26635
    extract = tar
    extract_path = verible-v0.0-4296-g0f262651/bin/verible-verilog-format
    [verible-verilog-format]
    group = verible-verilog-format
    marker = sys_platform == "linux" and platform_machine == "arm64"
    url = https://github.com/chipsalliance/verible/releases/download/v0.0-4296-g0f262651/verible-v0.0-4296-g0f262651-linux-static-arm64.tar.gz
    sha256 = e4a70e9920b6a24ce35045d4c9457d7d9185efc3c534a35ff55ef0262578b4e0
    extract = tar
    extract_path = verible-v0.0-4296-g0f262651/bin/verible-verilog-format
    [verible-verilog-format.exe]
    group = verible-verilog-format
    marker = sys_platform == "win32" and platform_machine == "AMD64"
    marker = sys_platform == "cygwin" and platform_machine == "x86_64"
    url = https://github.com/chipsalliance/verible/releases/download/v0.0-4296-g0f262651/verible-v0.0-4296-g0f262651-win64.zip
    sha256 = 4590841d91dadb108879aa261dbfd7081db06360484a7a21470174bf6fb3cf80
    extract = zip
    extract_path = verible-v0.0-4296-g0f262651-win64/verible-verilog-format.exe
    [verible-verilog-format]
    group = verible-verilog-format
    marker = sys_platform == "darwin" and platform_machine == "x86_64"
    marker = sys_platform == "darwin" and platform_machine == "arm64"
    url = https://github.com/chipsalliance/verible/releases/download/v0.0-4296-g0f262651/verible-v0.0-4296-g0f262651-macOS.tar.gz
    sha256 = fc397ee02b144184a3cce6d26efb8b9d3e41528e63c95a57cd3bf37dec2b52a4
    extract = tar
    extract_path = verible-v0.0-4296-g0f262651-macOS/bin/verible-verilog-format
